CREATE TABLE public.inf_pc
(
    id_pc integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_pc text COLLATE pg_catalog."default" NOT NULL,
    tag integer NOT NULL,
    cpu text COLLATE pg_catalog."default" NOT NULL,
    ram_gb integer NOT NULL,
    graphics_card text COLLATE pg_catalog."default" NOT NULL,
    hdd_gb integer NOT NULL,
    CONSTRAINT "Inf_PC_pkey" PRIMARY KEY (id_pc)
)

TABLESPACE pg_default;

ALTER TABLE public.inf_pc
    OWNER to postgres;

COMMENT ON TABLE public.inf_pc
    IS 'Сведения о ПК';

CREATE TABLE public.inf_software
(
    id_soft integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_soft text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    license text COLLATE pg_catalog."default" NOT NULL,
    num_license integer NOT NULL,
    CONSTRAINT "Inf_Software_pkey" PRIMARY KEY (id_soft)
)

TABLESPACE pg_default;

ALTER TABLE public.inf_software
    OWNER to postgres;

COMMENT ON TABLE public.inf_software
    IS 'Сведения о ПО';

CREATE TABLE public.inf_soft_pc
(
    id_soft_pc integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_pc integer NOT NULL,
    id_soft integer NOT NULL,
    CONSTRAINT "Inf_Soft_PC_pkey" PRIMARY KEY (id_soft_pc),
    CONSTRAINT soft_pc FOREIGN KEY (id_pc)
        REFERENCES public.inf_pc (id_pc) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT soft_soft FOREIGN KEY (id_soft)
        REFERENCES public.inf_software (id_soft) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.inf_soft_pc
    OWNER to postgres;

COMMENT ON TABLE public.inf_soft_pc
    IS 'Информация об установленном ПО на ПК';